export enum StyleType {
  camera = "camera",
  local = "local",
  cartFiled = "cartFiled",
  chat = "chat",
  search = "search",
  arrowUp = "arrowUp",
  arrowDown = "arrowDown",
  view = "view",
  arrowRight = "arrowRight",
  cartEmpty = "cartEmpty",
  edit = "edit",
  arrowRightSmall = "arrowRightSmall",
  arrowLeftSmall = "arrowLeftSmall",
  arrowRightBold = "arrowRightBold",
  star = "star",
  info = "info",
  user = "user",
  lock = "lock",
  github = "github",
  error = "error",
  success = "success",
  arrowRightDireactor = "arrowRightDireactor",
  huangguan = "huangguan",
  store = "store",
  close = "close",
}
